Pandas

In [3]:

import pandas as pd

In [4]:
salary=pd.read_csv('/content/Salary_Data.csv')

In [5]:
print(salary)

       Age  Gender    Education Level              Job Title  \
0     32.0    Male         Bachelor's      Software Engineer
1     28.0  Female           Master's           Data Analyst
2     45.0    Male                PhD         Senior Manager
3     36.0  Female         Bachelor's        Sales Associate
4     52.0    Male           Master's               Director
...    ...     ...                ...                    ...
6699  49.0  Female                PhD  Director of Marketing
6700  32.0    Male        High School        Sales Associate
6701  30.0  Female  Bachelor's Degree      Financial Manager
6702  46.0    Male    Master's Degree      Marketing Manager
6703  26.0  Female        High School        Sales Executive

      Years of Experience    Salary
0                     5.0   90000.0
1                     3.0   65000.0
2                    15.0  150000.0
3                     7.0   60000.0
4                    20.0  200000.0
...                   ...       ...
6699                 20.0  200000.0
6700                  3.0   50000.0
6701                  4.0   55000.0
6702                 14.0  140000.0
6703                  1.0   35000.0

[6704 rows x 6 columns]

In [7]:
salary.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [8]:
salary.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [9]:
salary.shape

(6704, 6)

In [11]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 314.4+ KB

In [15]:
salary.describe()

               Age  Years of Experience         Salary
count  6702.000000          6701.000000    6699.000000
mean     33.620859             8.094687  115326.964771
std       7.614633             6.059003   52786.183911
min      21.000000             0.000000     350.000000
25%      28.000000             3.000000   70000.000000
50%      32.000000             7.000000  115000.000000
75%      38.000000            12.000000  160000.000000
max      62.000000            34.000000  250000.000000

In [16]:
print(salary.columns)

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [19]:
print(salary['Salary'])

0        90000.0
1        65000.0
2       150000.0
3        60000.0
4       200000.0
          ...
6699    200000.0
6700     50000.0
6701     55000.0
6702    140000.0
6703     35000.0
Name: Salary, Length: 6704, dtype: float64

Cleaning

In [23]:
salary.isnull().sum().sum()

np.int64(17)

In [25]:
salary.fillna(bfill=True,inplace=True)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'bfill'

In [27]:
salary.dropna()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [33]:
df=salary.dropna()

In [32]:
salary.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [35]:
salary.fillna(method="bfill",inplace=True)

/tmp/ipykernel_1313/418410658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  salary.fillna(method="bfill",inplace=True)

In [39]:
data={
    "exp year":[1,2,3,4,5,6,7,8,9,10],"salary":[10000,20000,30000,40000,50000,60000,70000,80000,90000,100000]
}
df1=pd.DataFrame(data)

In [40]:
df1

   exp year  salary
0         1   10000
1         2   20000
2         3   30000
3         4   40000
4         5   50000
5         6   60000
6         7   70000
7         8   80000
8         9   90000
9        10  100000

In [41]:
df1.nunique()

exp year    10
salary      10
dtype: int64

In [42]:
df1.drop_duplicates()

   exp year  salary
0         1   10000
1         2   20000
2         3   30000
3         4   40000
4         5   50000
5         6   60000
6         7   70000
7         8   80000
8         9   90000
9        10  100000